# FONTS
font_family             JetBrains Mono Nerd Font
font_size               10.0
bold_font               auto
italic_font             auto
bold_italic_font        auto


# CURSOR
cursor_shape            beam
cursor_trail            1

# SCROLLBACK
scrollbar               scrolled
scrollbar_width         1
scrollback_lines        2000

# WINDOW PADDING
window_padding_width    12
background_opacity	0.7
