-- require("configs.variables")
require("configs.keybindings.application")
require("configs.keybindings.windows")
require("configs.keybindings.workspace")
require("configs.keybindings.media")
require("configs.keybindings.mouse")